### ISSUE TITLE
Fix the upper NavBar

### ISSUE THREAD

**Issue by pradumangoyal** [IMGIITRoorkee/omniport-frontend-faculty-profile#9]
Can the upper NAvBar be fixed while scrolling? As the whole page can be too long and navigation can become a little tough. I have tried to apply the following CSS and it's looking like the attached screenshot.
### CSS on 1st child div of the `12 wide column`
```css
selestor {
    position: sticky;
    top: 0;
    z-index: 50;
}
```

### Scrrenshot
![image](https://user-images.githubusercontent.com/34851451/86319770-e4315580-bc52-11ea-8462-5329793d4082.png)
